[project]
name = "venvception"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "click"
]

[tool.ruff]
line-length = 120

[tool.basedpyright]
reportAny = false
reportUnusedCallResult = false
